GET http://127.0.0.1:5000/ HTTP/1.1

###

POST http://127.0.0.1:5000/upload?name=tabla.csv&size=136&chunkIndex=0&totalChunks=1 HTTP/1.1
Content-Type: application/octet-stream

###

GET http://127.0.0.1:5000/headers?ext=csv HTTP/1.1

###

POST http://127.0.0.1:5000/analize HTTP/1.1
Content-Type: application/json

{
    "ext": "csv",
    "config": {
        "idxAlgorithm": 0,
        "algorithm": "Regresión lineal",
        "option": [
            "Graficar puntos",
            "Función de tendencia",
            "Predicción de tendencia"
        ]
    },
    "params": {
        "dependiente": "Solola",
        "independiente": "Ano",
        "time": "2025"
    }
}

###

POST http://127.0.0.1:5000/analize HTTP/1.1
Content-Type: application/json

{
    "ext": "csv",
    "config": {
        "idxAlgorithm": 0,
        "algorithm": "Regresión polinomial",
        "option": [
            "Graficar puntos",
            "Función de tendencia",
            "Predicción de tendencia"
        ]
    },
    "params": {
        "dependiente": "Solola",
        "independiente": "Ano",
        "time": "2025"
    }
}

###

POST http://127.0.0.1:5000/analize HTTP/1.1
Content-Type: application/json

{
    "ext": "csv",
    "config": {
        "idxAlgorithm": 0,
        "algorithm": "Clasificador gaussiano",
        "option": [
            "Graficar puntos"
        ]
    },
    "params": {
        "dependiente": "",
        "independiente": "play",
        "time": [0, 0, 0, 0]
    }
}

###

POST http://127.0.0.1:5000/analize HTTP/1.1
Content-Type: application/json

{
    "ext": "csv",
    "config": {
        "idxAlgorithm": 0,
        "algorithm": "Clasificador de árboles de decisión",
        "option": [
            "Graficar puntos"
        ]
    },
    "params": {
        "dependiente": "",
        "independiente": "play",
        "time": ""
    }
}

###

POST http://127.0.0.1:5000/analize HTTP/1.1
Content-Type: application/json

{
    "ext": "csv",
    "config": {
        "idxAlgorithm": 0,
        "algorithm": "Redes neuronales",
        "option": [
            "Graficar puntos"
        ]
    },
    "params": {
        "dependiente": "",
        "independiente": "",
        "time": ""
    }
}